name: Test
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dotnet
    uses: actions/setup-dotnet@v6
    with:
      dotnet-version: 6.0.x
    - name: Restore packages
    run: dotnet restore ${{ secrets.MAINPROJECT_PATH }}
    - name: Build project
    run: dotnet build ${{ secrets.MAINPROJECT_PATH }} --no-restore Release
    - name: Pack project
    run: dotnet pack ${{ secrets.MAINPROJECT_PATH }} --no-resore --no-build --configuration Release --include-symbols --output ${{ github.workspace }}\output
    - name: Push package
    run: dotnet nuget push ${{ github.workspace }}\output\*.nupkg -k ${{ secrets.NUGETKEY }} -s ${{ secrets.NUGET_SOURCE }}
