name: Test
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dotnet
    uses: actions/setup-dotnet@v6
    with:
      dotnet-version: 6.0.x
