name: Test
on:
  workflow_dispatch:
  
jobs:
  log:
    runs-on: windows-latest
    
    steps:
      - name: Create annotation for build error
        run: echo "::error file=app.js,line=1::Missing semicolon"
