name: "Deploy to Nuget"

on: ["push"]

jobs:
	deploy:
		name: 'Deploy'
		runs-on: 'windows-latest'
		steps:
		- name: 'Checkout'
		  uses: actions/checkout@v2

		- name: 'Install dotnet'
		  uses: actions/setup-dotnet@v6
		  with:
			dotnet-version: '6.0.x'

		- name: 'Restore packages'
		run: dotnet restore ${{ env.MAINPROJECT_PATH }}

		- name: 'Build project'
		run: dotnet build ${{ env.MAINPROJECT_PATH }} --no-restore Release

		- name: 'Pack project'
		run: dotnet pack ${{ env.MAINPROJECT_PATH }} --no-resore --no-build --configuration Release --include-symbols --output ${{ github.workspace }}\output

		- name: "Push package"
		run: dotnet nuget push ${{ github.workspace }}\output\*.nupkg -k ${{ secrets.NUGETKEY }} -s ${{ env.NUGET_SOURCE }}