name: "Deploy to Nuget"

on: ["push"]

env:
	PACKAGE_OUTPUT: ${{ github.workspace }}\output
	NUGET_SOURCE : ''https://api.nuget.org/v3/index.json''
	MAINPROJECT_PATH: CMouss.Alchemy/CMouss.Alchemy.csproj

jobs:
	deploy:
		name: 'Deploy'
		runs-on: 'windows-latest'
		steps:
		- name: 'Checkout'
		  uses: actions/checkout@v2

		- name: 'Install dotnet'
		  uses: actions/setup-dotnet@v6
		  with:
			dotnet-version: '6.0'

		- name: 'Restore packages'
		run: dotnet restore ${{ env.MAINPROJECT_PATH }}

		- name: 'Build project'
		run: dotnet build ${{ env.MAINPROJECT_PATH }} --no-restore Release

		- name: 'Pack project'
		run: dotnet pack ${{ env.MAINPROJECT_PATH }} --no-resore --no-build --configuration Release --include-symbols --output ${{ env.PACKAGE_OUTPUT }}

		- name: "Push package"
		run: dotnet nuget push ${{ env.PACKAGE_OUTPUT }}\*.nupkg -k ${{ secrets.NUGETKEY }} -s ${{ env.NUGET_SOURCE }}